/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minicompilador;

import java.util.LinkedList;

/**
 *
 * @author Moises
 */
public class Portada extends javax.swing.JFrame {

    /**
     * Creates new form Protada
     */
    BNF bnf = new BNF();
     Lexico lex = new Lexico();      
    public Portada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lexico = new javax.swing.JButton();
        sintactico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingresacodigo = new javax.swing.JTextArea();
        limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reconocecodigo = new javax.swing.JTextArea();
        salir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        errores = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JtxSintactico = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lexico.setBackground(new java.awt.Color(204, 255, 255));
        lexico.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lexico.setForeground(new java.awt.Color(255, 0, 0));
        lexico.setText("LEXICO");
        lexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexicoActionPerformed(evt);
            }
        });
        getContentPane().add(lexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 100, -1));

        sintactico.setBackground(new java.awt.Color(204, 255, 255));
        sintactico.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        sintactico.setForeground(new java.awt.Color(255, 0, 0));
        sintactico.setText("SINTACTICO");
        sintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintacticoActionPerformed(evt);
            }
        });
        getContentPane().add(sintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, -1));

        ingresacodigo.setColumns(20);
        ingresacodigo.setRows(5);
        jScrollPane1.setViewportView(ingresacodigo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 174, 215, 149));

        limpiar.setBackground(new java.awt.Color(204, 255, 255));
        limpiar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 0, 0));
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));

        reconocecodigo.setColumns(20);
        reconocecodigo.setRows(5);
        jScrollPane2.setViewportView(reconocecodigo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 174, 299, 149));

        salir.setBackground(new java.awt.Color(204, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 0, 0));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 80, -1));

        errores.setColumns(20);
        errores.setRows(5);
        jScrollPane3.setViewportView(errores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 433, 215, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE CARACTERES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CARACTERES RECONOCIDOS POR EL LENGUAJE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 299, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TABLA DE ERRORES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        JtxSintactico.setColumns(20);
        JtxSintactico.setRows(5);
        jScrollPane4.setViewportView(JtxSintactico);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 433, 299, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SINTACTICO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 76, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("MINI COMPILADOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO/dribbble-shot_6.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexicoActionPerformed
        // BOTON LEXICO
              lex.Lexico(ingresacodigo.getText());
             reconocecodigo.setText(lex.Recorrer.toString());
              errores.setText(lex.Error.toString());
            
    }//GEN-LAST:event_lexicoActionPerformed

    private void sintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintacticoActionPerformed
       //  lex.Lexico(ingresacodigo.getText()); 
      bnf.Sintactico(ingresacodigo.getText());
        JtxSintactico.setText(bnf.mostrar);
        errores.setText(bnf.errores.toString());
     
    }//GEN-LAST:event_sintacticoActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // BOTON LIMPIAR
        ingresacodigo.setText("");
        bnf.limpiartoken();
        lex.tokens.clear();
        JtxSintactico.setText("");
       reconocecodigo.setText("");
       errores.setText(" ");
    }//GEN-LAST:event_limpiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtxSintactico;
    private javax.swing.JTextArea errores;
    private javax.swing.JTextArea ingresacodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lexico;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea reconocecodigo;
    private javax.swing.JButton salir;
    private javax.swing.JButton sintactico;
    // End of variables declaration//GEN-END:variables
}
